### ISSUE TITLE
YML file support

### ISSUE THREAD

**Issue by PhoenixBound** [Herringway/ebbinex#1]
Hello, it's been a while. Wanted to try bringing ebsrc up to date with some subroutine names, but it looks like there was an update to ebbinex back in November that changed how the dumping works to be much nicer. This repo only appears to have code/binaries for the version from May that doesn't support YML files.

**Comment by Herringway** [comment]
I knew I was forgetting something...

**Comment by Herringway** [comment]
alright, uploaded the missing goods. also updated the ebsrc readme to accommodate the changes.
