### ISSUE TITLE
core.exception.RangeError@..\..\Libraries\compy\source\compy\hal.d(231): Range violation

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [Herringway/ebbinex#3]
After decompiling the ROM with a YML. I got another error:
`core.exception.RangeError@..\..\Libraries\compy\source\compy\hal.d(231): Range violation`

**Comment by Herringway** [comment]
sounds like it's trying to decompress something that isn't compressed data. is this a clean rom?

**Comment by LucianoTheWindowsFan** [comment]
Yup. I was using the _MOTHER 2_ Japanese ROM as an attempt to translate the original into English, given the American version (_EarthBound_) is filled with a LOT of censorship.

**Comment by Herringway** [comment]
I cannot reproduce this. make sure you're using a clean rom (SHA1 hash of 8738CFF9E38A8B86AE30BFE0E5FBCB2828C2B16E), latest mother2.yml and ebbinex binary. nothing else is supported
