### ISSUE TITLE
commondefs.yml: No such file or directory

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/ebbinex#5]
I'm trying to use this on Linux.  I've compiled it but when I run the program without any arguments, it outputs `Usage: ./ebbinex <path to dump doc> <path to rom>`.  However I don't have a dump doc yet, I want to create one.  But when I run `./ebbinex EarthBound.sfc test` (`test` being an empty directory I created):

```plain
std.file.FileException@std/file.d(370): commondefs.yml: No such file or directory
----------------
??:? @safe bool std.file.cenforce!(bool).cenforce(bool, scope lazy const(char)[], immutable(char)[], ulong) [0x555e02401be8]
??:? @trusted void[] std.file.readImpl(scope const(char)[], scope const(char)*, ulong) [0x555e02400c54]
/usr/include/dmd/phobos/std/file.d:319 @safe void[] std.file.read!(immutable(char)[]).read(immutable(char)[], ulong) [0x555e022c5401]
/usr/include/dmd/phobos/std/file.d:516 @safe immutable(char)[] std.file.readText!(immutable(char)[], immutable(char)[]).readText(ref immutable(char)[]) [0x555e022c5248]
../../.dub/packages/siryul-0.8.1/siryul/source/siryul/siryul.d:47 @safe common.CommonData siryul.siryul.fromFile!(common.CommonData, siryul.dyaml.YAML, 0).fromFile(immutable(char)[]) [0x555e022c51f4]
source/app.d:27 _Dmain [0x555e022b0baa]
```

I've tried passing the `-z` argument but that doesn't effect anything, and the README just says to pass one argument, the EarthBound rom, but doing so just causes it to print the usage.

**Comment by Herringway** [comment]
It looks for commondefs.yml in the current directory.

**Comment by Anonymous941** [comment]
> It looks for commondefs.yml in the current directory.

@Herringway Where is this file from?

**Comment by Herringway** [comment]
it's bundled with the earthbound disassembly

**Comment by Anonymous941** [comment]
Then how do I disassemble it, as opposed to reassembling?  I currently have a ROM, not YML files.

**Comment by Herringway** [comment]
this tool is designed to be used with the disassembly and is run from its directory

**Comment by Anonymous941** [comment]
Are you referring to Yoshifanatic1/EarthBound-Disassembly?

**Comment by Herringway** [comment]
I'm referring to https://github.com/Herringway/ebsrc.

**Comment by Anonymous941** [comment]
Okay, you might want to put that in the README, currently it says it only requires a path to the ROM.  Thank you, I extracted the resources now.
